name: Run Spider

on:
  workflow_dispatch:  # 手動觸發
  schedule:           # 定時觸發（每天台灣時間 09:00）
    - cron: '0 * * * *'

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true  # 若沒有 requirements.txt 會略過
        pip install pandas requests beautifulsoup4

    - name: Run api.py
      run: python api.py

    - name: Run static.py
      run: python static.py
