name: Run Spider

on:
  workflow_dispatch:  # 手動觸發
  schedule:           # 每小時執行一次（UTC 0 分）
    - cron: '0 * * * *'

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true  # 若沒有 requirements.txt 會略過
        pip install pandas requests beautifulsoup4

    - name: Run api.py
      run: python api.py

    - name: Run static.py
      run: python static.py

    - name: Commit CSV results
      run: |
        git config --global user.email "Allen20040209@gmail.com"
        git config --global user.name "allenwhitewho"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add *.csv
        git commit -m "chore: update CSV data from workflow every hour" || echo "No changes to commit"
        git push origin HEAD